# Generated by Django 3.0 on 2019-12-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugs',
            old_name='status',
            new_name='fixed',
        ),
    ]
