# Generated by Django 3.0.3 on 2020-02-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191216_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='title',
            field=models.CharField(default='morjens', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bug',
            name='priority',
            field=models.CharField(choices=[('RED', 'High'), ('YELLOW', 'Medium'), ('GREEN', 'Low')], max_length=10),
        ),
    ]
