# Generated by Django 3.0.3 on 2020-03-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200217_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10),
        ),
    ]
