# Generated by Django 3.0.3 on 2020-03-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200301_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
