# Generated by Django 3.0.4 on 2020-03-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_profile'),
        ('app', '0008_auto_20200317_1643'),
    ]

    operations = [
    ]
