# Generated by Django 3.0.5 on 2020-04-09 11:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20200322_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='voters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), default=list, size=None),
        ),
    ]
