# Generated by Django 3.0.5 on 2020-04-10 12:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200409_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='voters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), default=list, size=None),
        ),
    ]
