# Generated by Django 3.0.5 on 2020-04-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_bug_voters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='kuva'),
        ),
    ]
